---
- name: Установка Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  
- name: Настройка конфигурации Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: restart nginx
  
- name: Настройка сайта по умолчанию
  template:
    src: default-site.j2
    dest: /etc/nginx/sites-available/default
    mode: '0644'
  notify: restart nginx
  
- name: Создание пользовательской страницы
  copy:
    content: |
      <html>
        <head><title>Ansible Lab - NGINX Role</title></head>
        <body>
          <h1>Лабораторная работа по Ansible</h1>
          <p>Роль NGINX успешно применена</p>
          <p>Студент: {{ student_name }}</p>
          <p>Дата: {{ ansible_date_time.date }}</p>
        </body>
      </html>
    dest: /var/www/html/index.html
    mode: '0644'
  notify: restart nginx
